ScrollReveal().reveal('.banner', {delay: 200});
ScrollReveal().reveal('#llamado-accion', {delay: 500});
ScrollReveal().reveal('.portafolio', {delay: 500});
ScrollReveal().reveal('#servicios', {delay: 500});
ScrollReveal().reveal('#clientes', {delay: 500});
ScrollReveal().reveal('#formulario', {delay: 500});
ScrollReveal().reveal('#texto_formulario', {delay: 500});
ScrollReveal().reveal('#agndar_cita', {delay: 500});
ScrollReveal().reveal('#pie-pagina', {delay: 500});